# What is NumPy?

1. NumPy is a Python library used for working with arrays.

2. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

3. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

4. NumPy stands for Numerical Python.

5. Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of

high-level mathematical functions to operate on these arrays.

# Why Use NumPy?

1. In Python we have lists that serve the purpose of arrays, but they are slow to process.

2. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

3. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

4. Arrays are very frequently used in data science, where speed and resources are very important.

5. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.This behavior is called

 locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

 

In [ ]:
pip install numpy       # prefered intaller programme

In [1]:
import numpy 

In [2]:
#creating an array
import numpy

arr = numpy.array([1, 2, 3, 4, 5])              ## convert python list into numpy arrays

print(arr)

[1 2 3 4 5]


In [3]:
#NumPy is usually imported under the np alias.
#[alias: In Python alias are an alternate name for referring to the same thing.]
import numpy as np        #Now the NumPy package can be referred to as np instead of numpy.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np

print(np.__version__)             # to check the version of numpy


1.20.1


#Creating Numpy Arrays

1. Create NumPy Arrays from list, tuple or list of lists

2. Create NumPy Arrays from a range of evenly spaced numbers using np.arrange().

3. Create NumPy Array of zeros (0's) using np.zeros()

4. Create 1D / 2D NumPy Array filled with ones (1's) using np.ones()

5. Create NumPy Array of different shapes & initialize with identical values using numpy.full()

6. Create NumPy Array with same sized samples over an interval in Python using numpy.linspace()

7. Create a NumPy Array of bool value.

In [ ]:
# command : np.array() : Create Numpy Array from list, tuple or list of lists in Python

# Use : to create a Numpy Array from an another array like object in python like list or tuple etc or any nested sequence like list of list,

# syntax : 

numpy.array(object, dtype=None, copy=True, order='K')

#Arguments:   

1. object is an array like object i.e. list or tuple or any nested sequence like list of list.

2. dtype: (Optional) Data type of elements

3. Other parameters are optional and has default values.

#Returns:

It returns a Numpy Array .

In [6]:
#Create Numpy Array from a list
#To create a Numpy Array from list just pass the list object to numpy.array() i.e.

npArray = np.array([1,2,3,4,5,6,7,8,9])
print(npArray)

#Create Numpy Array from a tuple
#Similar to above example, we can directly pass the tuple to the numpy.array() to create a Numpy Array object,

npArray = np.array( (11,22,33,44,55,66,77,88 ) )
print(npArray)
print(type(npArray))              # to check type of the array

[1 2 3 4 5 6 7 8 9]
[11 22 33 44 55 66 77 88]
<class 'numpy.ndarray'>


In [7]:
#Check the data type of elements in Numpy Array???
#Numpy  Array has a member variable that tells about the datatype of elements in it i.e. ndarray.dtype.

#We created the Numpy Array from the list or tuple. While creating numpy.array() will deduce the data type of the elements based on input passed.
#But we can check the data type of Numpy Array elements i.e.

print('Data Type of elements in  ndArray : ')
npArray = np.array((11, 22, 33, 44, 55, 66, 77, 88))
print(npArray.dtype)

Data Type of elements in  ndArray : 
int32


In [8]:
#Create a Numpy Array from a list with different data type
#We can also pass the dtype as parameter in numpy.array(). In that case numpy.array() will not deduce the data type from passed elements, it convert them to passed data type.

#For example pass the dtype as float with list of int i.e.

# Create ndArray of float datatype from a list of int
npArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9] , dtype=str)
print('Contents of the ndArray : ', npArray)
print('Type of the ndArray : ', npArray.dtype)

Contents of the ndArray :  ['1' '2' '3' '4' '5' '6' '7' '8' '9']
Type of the ndArray :  <U1


#Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

[nested array: are arrays that have arrays as their elements.]

1. 0-D Arrays

2. 1-D Arrays

3. 2-D Arrays

4. 3-D arrays

5. higher dimension Arrays

In [9]:
#0-D Arrays
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

import numpy as np

arr = np.array(42)                #0-D array with value 42

print(arr)

42


In [10]:
#1-D Arrays
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
#These are the most common and basic arrays.
#Example
import numpy as np

arr = np.array([1, 2, 3, 4, 5])                 # 1-D array containing the values 1,2,3,4,5:
print('1-D array containing the values :')
print(arr)

#Create 1D Numpy Array of given length and filled with zeros
# command : 
#Suppose we want to create a numpy array of five zeros (0s). For that we need to call the numpy.zeros() function with argument 5 i.e.

arr = np.zeros(5)
print('1D Numpy Array of given length and filled with zeros :')
print(arr)
print(type(arr))

#Create Numpy array of zeros of integer data type
#By default numpy.zeros() returns a numpy array of float zeros. But if we want to create a numpy array of zeros as integers, then we can pass the data type 
#too in the zeros() function. For example,

arr = np.zeros(5, dtype=np.int64)
print('Numpy array of zeros of integer data type :')
print(arr) 

# command : np.ones() – Create 1D / 2D Numpy Array filled with ones (1’s)
#[numpy.ones()
#Python’s Numpy module provides a function to create a numpy array of given shape & type and filled with 1’s i.e,

#numpy.ones(shape, dtype=float, order='C')
#Arguments:

#shape: Shape of the numpy array. Single integer or sequence of integers.
#dtype: (Optional) Data type of elements. Default is float64.
#order: (Optional) Order in which data is stored in multi-dimension array i.e. in row major(‘F’) or column major (‘C’). Default is ‘C’.

#Returns:

#It returns a numpy array of given shape but filled with ones.

#Create 1D Numpy Array of given length and filled with ones
#Suppose we want to create a numpy array of five ones (1s). For that we need to call the numpy.ones() function with argument 5 i.e.

arr = np.ones(5)
print('1D Numpy Array of given length and filled with ones :')
print(arr)

#Create numpy array with ones of integer data type
#By default numpy.ones() returns a numpy array of float ones. But if we want to create a numpy array of ones as integers, then we can pass the data type too in the ones() function. For example,

arr = np.ones(5, dtype=np.int64)
print('umpy array with ones of integer data type :')
print(arr)

1-D array containing the values :
[1 2 3 4 5]
1D Numpy Array of given length and filled with zeros :
[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
Numpy array of zeros of integer data type :
[0 0 0 0 0]
1D Numpy Array of given length and filled with ones :
[1. 1. 1. 1. 1.]
umpy array with ones of integer data type :
[1 1 1 1 1]


In [11]:
#Create 1D Numpy Array from list of list
#On passing a list of list to numpy.array() will create a 2D Numpy Array by default. But if we want to create a 1D numpy array from list of list then we need to merge lists of lists to a single list and then pass it to numpy.array() i.e.

listOfLists = [[[77, 88, 99], [31, 42, 63], [11, 22, 33]]]

npArray = np.array([ elem for singleList in listOfLists for elem in singleList])

print(npArray)


[[77 88 99]
 [31 42 63]
 [11 22 33]]


In [12]:
 for singleList in listOfLists :
   print(singleList)

[[77, 88, 99], [31, 42, 63], [11, 22, 33]]


In [13]:
#2-D Arrays
#An array that has 1-D arrays as its elements is called a 2-D array.
#These are often used to represent matrix or 2nd order tensors.
#NumPy has a whole sub module dedicated towards matrix operations called numpy.mat



import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])            # 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
print('2-D array containing two arrays :')
print(arr)


#Create two dimensional (2D) Numpy Array of zeros
#To create a multidimensional numpy array filled with zeros, we can pass a sequence of integers as the argument in zeros() function. For example, 
#to create a 2D numpy array or matrix of 4 rows and 5 columns filled with zeros, pass (4, 5) as argument in the zeros function.

arr_2d = np.zeros( (4, 5) , dtype=np.int64)
print(' two dimensional (2D) Numpy Array of zeros :')
print(arr_2d)


#Create two dimensional (2D) Numpy Array of ones
#To create a multidimensional numpy array filled with ones, we can pass a sequence of integers as the argument in ones() function. For example, to create a 2D numpy array or matrix of 4 rows and 5 columns filled with ones, pass (4, 5) as argument in the ones() function.

arr_2d = np.ones( (4, 5) , dtype=np.int64)
print('two dimensional (2D) Numpy Array of ones :')
print(arr_2d)

2-D array containing two arrays :
[[1 2 3]
 [4 5 6]]
 two dimensional (2D) Numpy Array of zeros :
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
two dimensional (2D) Numpy Array of ones :
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#Create 2D Numpy Array from a list of list
#Suppose we want to create 2D Numpy Array like Matrix, we can do that by passing a nested sequence in numpy.array() i.e. list of list.
#For example,


npArray = np.array( [ [77, 88, 99] , [31,42,63] , [11,22,33]])        # Create 2D ndarray form list of list
print('Contents of the ndArray : ')
print(npArray)

In [14]:
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor. 

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])      
#3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
print('3-D array with two 2-D arrays :')
print(arr)


#Create 3D Numpy Array filled with zeros
#To create a 3D Numpy array filled with zeros, pass the dimensions as the argument in zeros() function. For example,

arr_3d = np.zeros( (2, 4, 5) , dtype=np.int64)
print('3D Numpy Array filled with zeros :')
print(arr_3d)

##Create 3D Numpy Array filled with ones
#To create a 3D Numpy array filled with ones, pass the dimensions as the argument in ones() function. For example,

arr_3d = np.ones( (2, 4, 5) , dtype=np.int64)
print('3D Numpy Array filled with ones :')
print(arr_3d)

3-D array with two 2-D arrays :
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3D Numpy Array filled with zeros :
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
3D Numpy Array filled with ones :
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
#Higher Dimensional Arrays
#An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.

import numpy as np

arr = np.array([[[[[1, 2, 3, 4]]]]], ndmin=3)       #an array with 5 dimensions 

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
#To Check Number of Dimensions
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.


import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
#2. command : numpy.arange() : Create a Numpy Array of evenly spaced numbers in Python
# Use :  how to create a Numpy array of evenly spaced numbers over a given interval using numpy.arrange().
# Syntax : 
numpy.arange([start, ]stop, [step, ]dtype=None)

#Arguments:

#1. start : It’s the start value of range. It’s optional, if not provided default value be 0.

#2. stop : End Value of range, array. It doesn’t include this value but it’s an end marker

#3. step : Spacing between two adjacent values. It’s optional, if not provided default value be 1.

#4. dtype : Data type of elements.If not provided will be deduced from other arguments.

#This function returns an evenly spaced array of numbers from range start to stop -1 with equal intervals of step.

SyntaxError: invalid syntax (<ipython-input-16-be0353dddc45>, line 4)

In [17]:
#Create a Numpy Array containing numbers from 5 to 30 but at equal interval of 2
#Here, start of Interval is 5, Stop is 30 and Step is 2 i.e.
# example 
import numpy as np
# Start = 5, Stop = 30, Step Size = 2
arr = np.arange(5, 30, 2)
print('containing numbers from 5 to 30 but at equal interval of 2 :')
print(arr)

# 2. Example 2:

#Create a Numpy Array containing elements from 1 to 10 with default interval i.e. 1
#As step argument is option, so when it is not provided then it’s default value will be 1.

import numpy as np
# Start = 1, Stop = 10. As Step Size is not provided, so default value be 1
arr = np.arange(1, 10)
print('containing elements from 1 to 10 :')
print(arr)


#Example 3:

#Create a Numpy Array containing elements up to 20 with default start and step size
#As start & step arguments are optional, so when we don’t provide these arguments then there default value will be 0 & 1.
#Let’s create a Numpy array with default start & step arguments,  stop of interval is 20 i.e.

import numpy as np
# Stop = 20. As Start and Step Size is not provided, so default value be 0 and 1 respectively
arr = np.arange(20)
print('3. containing elements upto 20 :')
print(arr)

containing numbers from 5 to 30 but at equal interval of 2 :
[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
containing elements from 1 to 10 :
[1 2 3 4 5 6 7 8 9]
3. containing elements upto 20 :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
# command : numpy.full(): Create Numpy Array of different shapes & initialize with identical values using numpy.full()

# Use :how to create a Numpy Array of different shapes and initialized with same identical values using numpy.full().

#numpy.full()

#Python’s Numpy module provides a function to create a numpy array of given shape and all elements initialized with a given value,
#syntax : numpy.full(shape, fill_value, dtype=None, order='C')

#Arguments:
#1. shape: Shape of the new array
#2. fill_value : Intialization value
#3. dtype : Data type of elements | Optional

#Example 1:

# Create a 1D Numpy Array of length 10 & all elements initialized with value 5
arr = np.full(10, 5)
print('1D Numpy Array of length 10 :')
print(arr)
# comment : Data Type of Contents of the Numpy Array : int32 , Shape of the Numpy Array : (10,)

#Example 2:

#Create a 2D Numpy Array of 4 rows & 5 columns. All intialized with value 7
arr = np.full((4,5), 7)
print('2D Numpy Array of 4 rows | 5 columns & all elements initialized with value 7 is :')
print(arr)
# comment : Data Type of Contents of the Numpy Array : int32 , Shape of the Numpy Array : (4,5)

#Example 3:

# Create a 3D Numpy array & all elements initialized with value 8
arr = np.full((2,4,5), 8)
print('3D Numpy Array of shape (2,4,5) & all elements initialized with value 8 is :')
print(arr)

1D Numpy Array of length 10 :
[5 5 5 5 5 5 5 5 5 5]
2D Numpy Array of 4 rows | 5 columns & all elements initialized with value 7 is :
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
3D Numpy Array of shape (2,4,5) & all elements initialized with value 8 is :
[[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]]


In [20]:
# command : Numpy.linspace():Create same sized samples over an interval

#Use :  function to create a evenly spaced samples over a specified interval 

#syntax :

#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

#Arguments:

#start : It’s the start of Sequence / range.

#stop : End Value of range, array doesn’t include this value but it’s an end marker

#num : Numbers of samples to be generated. It’s optional, if not provided default value will be 50.

#dtype : Data type of elements, if not provided will be deduced from other arguments.

#It returns num number of evenly spaced samples over the range [start, stop)

In [21]:
#Example 1:
import numpy as np
# Create 5 evenly spaced samples in interval [20, 60}
arr = np.linspace(20,60, 5)
print('5 evenly spaced samples in interval :')
print(arr)
print(type(arr))
# OR
#Create 5 evenly spaced int samples in interval [20, 60}
arr = np.linspace(20, 60, 5 , dtype=np.int32)         # for integer type data 
print(arr)

5 evenly spaced samples in interval :
[20. 30. 40. 50. 60.]
<class 'numpy.ndarray'>
[20 30 40 50 60]


In [22]:
#Example 2:

#Get the Step size from numpy.linspace()
#If we pass the argument retstep=True in numpy.linspace() then it will return step size between samples too along with the Numpy array of samples
#Create evenly spaced samples in interval [20, 60} and also get the step size
arr , step = np.linspace(20, 60, 5, retstep=True)
print('Contents of the Numpy Array : ')
print(arr)
print('Step size between two elements  : ', step)

Contents of the Numpy Array : 
[20. 30. 40. 50. 60.]
Step size between two elements  :  10.0


In [23]:
#Create boolean Numpy array with all True or all False or random boolean values
#Create boolean Numpy array with random boolean values
#To create a boolean numpy array with random values use a function random.choice() from python’s numpy module,
numpy.random.choice(a, size=None, replace=True, p=None)

Arguments:
a: A Numpy array from which random sample will be generated
size : Shape of the array to be generated
replace : Whether the sample is with or without replacement


SyntaxError: invalid syntax (<ipython-input-23-6c632fbbf451>, line 6)

In [24]:
#create a boolean numpy array of size 10 with random bool values,
# Array for random sampling
sample_arr = [True, False]              # create boolen arrays with true and false then passed to function
# Create a numpy array with random True or False of size 10
bool_arr = np.random.choice(sample_arr, size=10)
print('Numpy Array: ')
print(bool_arr)

#Creating 2D boolean Numpy array with random values
#To create a 2D boolean Numpy array with random True or false values, we can use the same function by passing the size of 2D array as a tuple,
# Array for random sampling
sample_arr = [True, False]
# Create a 2D numpy array or matrix of 3 rows & 4 columns with random True or False values
bool_arr = np.random.choice(sample_arr, size=(3,4))
print('2D Numpy Array: ')
print(bool_arr)


#To Create a boolean numpy array with all True values, we can use numpy.ones() with dtype argument as bool,
# Create a Numpy array of 10 True values
bool_arr = np.ones(10, dtype=bool)              #Create a Bool array with all True
print('Numpy Array with all true values : ')
print(bool_arr)

#To Create a boolean numpy array with all False values, we can use numpy.zeros() with dtype argument as bool,
# Create a Numpy array of 10 False values
bool_arr = np.zeros(10, dtype=bool)
print('Numpy Array with all false values: ')
print(bool_arr)

# Create a 2D Numpy array of 3 rows & 4 columns with all True values
bool_arr = np.ones((3,4), dtype=bool)
print('2D Numpy Array with all true values: ')
print(bool_arr)

# Create a 2D Numpy array of 3 rows & 4 columns with all False values
bool_arr = np.zeros((3,4), dtype=bool)
print('2D Numpy Array with all false values: ')
print(bool_arr)

#Convert a list of integers to boolean numpy array
# List of integers
list_of_elems = [1, 2, 3, 0, 9, 0, 8, 0]
# Convert a list of integers to bool array
bool_arr = np.array(list_of_elems, dtype=bool)
print('Convert a list of integers to boolean numpy array: ')
print(bool_arr)


#Convert a heterogeneous list to boolean numpy array

#Lists are heterogeneous in python. It means it can contain elements of different data types. But Numpy Arrays in python are homogeneous, it means they can contain elements of the same data type. So, to convert a heterogeneous list to boolean numpy array, we will pass dtype argument as bool in the numpy.array() function,
# heterogeneous List ( contains different type of elements)
list_of_elems = [8, 0, 'Hi', '', 0.4]
# Convert a heterogeneous list to bool numpy array
bool_arr = np.array(list_of_elems, dtype=bool)
print(bool_arr)


Numpy Array: 
[ True  True  True False False False  True False False  True]
2D Numpy Array: 
[[False False False  True]
 [False False  True False]
 [ True False  True  True]]
Numpy Array with all true values : 
[ True  True  True  True  True  True  True  True  True  True]
Numpy Array with all false values: 
[False False False False False False False False False False]
2D Numpy Array with all true values: 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
2D Numpy Array with all false values: 
[[False False False False]
 [False False False False]
 [False False False False]]
Convert a list of integers to boolean numpy array: 
[ True  True  True False  True False  True False]
[ True False  True False  True]


# Adding Elements in Numpy Array

1. Append/ Add an element to Numpy Array in Python (3 Ways)

2. How to append elements at the end of a Numpy Array in Python using numpy.append()

3. Create an empty 2D Numpy Array / matrix and append rows or columns in python

#1.  Append/ Add an element to Numpy Array in using 

1.append() : to add an element to Numpy Array.

2.concatenate() to add an element to Numpy Array.



In [25]:
#Add element to Numpy Array using append()
#Numpy module in python, provides a function to numpy.append() to add an element in a numpy array. We can pass the numpy array and a single value as arguments to the append() function. It doesn’t modifies the existing array, but returns a copy of the passed array with given value added to it. For example,

import numpy as np
# Create a Numpy Array of integers
arr = np.array([11, 2, 6, 7, 2])
# Add / Append an element at the end of a numpy array
new_arr = np.append(arr, 10)
print('New Array: ', new_arr)
print('Original Array: ', arr)

#Add element to Numpy Array using concatenate()
#Numpy module in python, provides a function numpy.concatenate() to join two or more arrays. We can use that to add single element in numpy array. But for that we need to encapsulate the single value in a sequence data structure like list and pass a tuple of array & list to the concatenate() function. For example,

import numpy as np
# Create a Numpy Array of integers
arr = np.array([11, 2, 6, 7, 2])
# Add / Append an element at the end of a numpy array
new_arr = np.concatenate( (arr, [10] ) )
print('New Array: ', new_arr)
print('Original Array: ', arr)

New Array:  [11  2  6  7  2 10]
Original Array:  [11  2  6  7  2]
New Array:  [11  2  6  7  2 10]
Original Array:  [11  2  6  7  2]


In [26]:
# command : numpy.append(): 
#syntax :
numpy.append(arr, values, axis=None)
Arguments:

arr: array_like , Given values will be added in copy of this array.

values: array_like , Values that needs to be added in the array.
If axis is provided, then values to be added must be of similar shape as array arr along the axis where we want to add.

axis: int, optional
The axis along which values will be added to array. Default value is None.
If axis is None: Then values array will be flattened and added to the array arr.
If axis is 0, then values will be appended row wise.
If axis is 1, then values will be appended column wise.
Returns:

A copy of the given array arr, with values appended to the array.

SyntaxError: invalid syntax (<ipython-input-26-675ebad3ddb1>, line 4)

In [27]:
#Append elements at the end of 1D numpy array

import numpy as np
# create a Numpy array from a list
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Append a single element at the end of Numpy Array
newArr = np.append(arr, 88)
print('Append a single element at the end of Numpy Array:')
print(newArr)


import numpy as np
# create a Numpy array from a list
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Append multiple elements from a list to the end of a Numpy Array
newArr = np.append(arr, [88,99,100])
print('Append elements from a list to the Numpy array:')
print(newArr)


import numpy as np
# Create a 2D Numpy Array like Matrix
matrixArr = np.array( [ [1, 2, 3],
                        [ 4, 5, 6] ])
#Now append 1D list to this 2D Numpy array.
# Add elements in List to 2D Numpy array by flattening
newArr = np.append(matrixArr, [22, 23, 24])
print('Flatten 2D Numpy Array and added items to it :')
print(newArr)


#If we provide axis parameter in append() call then both the arrays should be of same shape. Let’s create two 2D numpy arrays,

import numpy as np
# Create two 2D Numpy Array like Matrix
matrixArr1 = np.array([[1, 2, 3],
                        [4, 5, 6]])
matrixArr2 = np.array([[70, 80, 90],
                         [61, 62, 63]])
newArr = np.append(matrixArr1, matrixArr2 , axis=1)
print('Create two 2D Numpy Array like Matrix:')
print(newArr)


#Add a NumPy Array to another array – Column Wise
#In the above example if instead of passing axis as 0 we pass axis=1 then contents of 2D array matrixArr2 will be appended to the contents of matrixArr1  as columns in new array i.e.

import numpy as np
# Create two 2D Numpy Array like Matrix
matrixArr1 = np.array([[1, 2, 3],
                        [4, 5, 6]])
matrixArr2 = np.array([[70, 80, 90],
                         [61, 62, 63]])
newArr = np.append(matrixArr1, matrixArr2 , axis=1)
print(newArr)




Append a single element at the end of Numpy Array:
[ 1  2  3  4  5  6  7 88]
Append elements from a list to the Numpy array:
[  1   2   3   4   5   6   7  88  99 100]
Flatten 2D Numpy Array and added items to it :
[ 1  2  3  4  5  6 22 23 24]
Create two 2D Numpy Array like Matrix:
[[ 1  2  3 70 80 90]
 [ 4  5  6 61 62 63]]
[[ 1  2  3 70 80 90]
 [ 4  5  6 61 62 63]]


In [28]:
# command : numpy.empty(): Create an empty 2D Numpy Array / matrix and append rows or columns
# Use : how to create an empty matrix or 2D numpy array first using numpy.empty() and then append individual rows or columns to this matrix using numpy.append().
# it creates a copy of the given numpy array arr and then appends the numpy array values to it along the given axis. 
#Then it returns this new array i.e. copy of arr but with appended values.
# syntax :

numpy.empty()

numpy.empty(shape, dtype=float, order='C')

It accepts shape and data type as arguments. Then returns a new array of given shape and data type but without initializing entries.

#numpy.append()
numpy.append(arr, values, axis=None)

It accepts following arguments,
arr: copy of array in which value needs to be appended
values: array which needs to be appended on any axis, It must be of same shape as arr.
axis: Axis along which values need to be appended. To append as row axis is 0, whereas to append as column it is 1.

SyntaxError: invalid syntax (<ipython-input-28-539d8d739781>, line 11)

In [29]:
#Create Empty Numpy array and append rows
# Create an empty Numpy array with 4 columns or 0 rows
empty_array = np.empty((0, 4), int)
print('Empty 2D Numpy array:')
print(empty_array)

#Now to append a new row to this empty 2D Numpy array, we can use the numpy.append(). But we need to pass the row as a numpy array of same shape only, 
#and pass axis=0, so that it can be appended along the column,
# Append a row to the 2D numpy array
empty_array = np.append(empty_array, np.array([[11, 21, 31, 41]]), axis=0)
# Append 2nd rows to the 2D Numpy array
empty_array = np.append(empty_array, np.array([[15, 25, 35, 45]]), axis=0)
print('Append 2nd rows to the 2D Numpy array:')
print(empty_array)


#Add multiple rows to an empty 2D Numpy array
#To add multiple rows to an 2D Numpy array, combine the rows in a same shape numpy array and then append it,
# Append multiple rows i.e 2 rows to the 2D Numpy array
empty_array = np.append(empty_array, np.array([[16, 26, 36, 46], [17, 27, 37, 47]]), axis=0)
print('multiple rows to an empty 2D Numpy array:')
print(empty_array)


#Create Empty Numpy array and append columns
# Create an empty 2D numpy array with 4 rows and 0 column
empty_array = np.empty((4, 0), int)
print('Empty 2D Numpy array:')
print(empty_array)
column_list_1 = [11, 21, 31, 41]
# Append list as a column to the 2D Numpy array
empty_array = np.append(empty_array, np.array([column_list_1]).transpose(), axis=1)
print('2D Numpy array:')
print(empty_array)
#So, one column is added to the empty numpy array. Now let’s add another column,
column_list_2 = [15, 25, 35, 45]
# Append list as a column to the 2D Numpy array
empty_array = np.append(empty_array, np.array([column_list_2]).transpose(), axis=1)
print('2D Numpy array:')
print(empty_array)

#Add multiple columns to an empty 2D Numpy array in single line
#To add multiple columns to an 2D Numpy array, combine the columns in a same shape numpy array and then append it,
# Create an empty 2D numpy array with 4 rows and 0 column
empty_array = np.empty((4, 0), int)
column_list_2 = np.array([[16, 26, 36, 46], [17, 27, 37, 47]])
# Append list as a column to the 2D Numpy array
empty_array = np.append(empty_array, column_list_2.transpose(), axis=1)
print('2D Numpy array:')
print(empty_array)

Empty 2D Numpy array:
[]
Append 2nd rows to the 2D Numpy array:
[[11 21 31 41]
 [15 25 35 45]]
multiple rows to an empty 2D Numpy array:
[[11 21 31 41]
 [15 25 35 45]
 [16 26 36 46]
 [17 27 37 47]]
Empty 2D Numpy array:
[]
2D Numpy array:
[[11]
 [21]
 [31]
 [41]]
2D Numpy array:
[[11 15]
 [21 25]
 [31 35]
 [41 45]]
2D Numpy array:
[[16 17]
 [26 27]
 [36 37]
 [46 47]]


# Searching in Numpy Arrays

1. the indexing in Numpy Array and finding it

2. Find max value & it’s index in Numpy Array | numpy.amax()

3. Find unique values in a numpy array with frequency & indice

4. numpy.amin() | Find minimum value in Numpy Array and it’s index

In [32]:
#NumPy Array Indexing
'''Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.'''

'Array indexing is the same as accessing an array element.\n\nYou can access an array element by referring to its index number.\n\nThe indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.'

In [33]:
#Creating sample array
arr = np.arange(2,15)
print(arr)

print('1.Second element of array:')
print(arr[1])

print('third and fourth elements from the array and add them: ')
print(arr[2]+arr[3])

arr[1:5]            # accessing 1 to 5 element from array
arr[:5]             # accessing from 1 to 5 elements




[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
1.Second element of array:
3
third and fourth elements from the array and add them: 
9


array([2, 3, 4, 5, 6])

In [34]:
import numpy as np
#Setting a value with index range (Broadcasting)
arr[0:5]=15

#Show
arr

array([15, 15, 15, 15, 15,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
#Slicing arrays
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].
import numpy as np
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
print('range of arrays :')
print(arr)

# slicing 
slice_of_arr = arr[0:6]

print('Show slice :')
print(slice_of_arr)

#Change Slice

slice_of_arr[:2]=50

print("Show Slice again :")
print(slice_of_arr)

range of arrays :
[ 0  1  2  3  4  5  6  7  8  9 10]
Show slice :
[0 1 2 3 4 5]
Show Slice again :
[50 50  2  3  4  5]


In [36]:
arr = np.arange(0,11)
print('range of arrays :')
print(arr)


#To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy


arr_copy[0:2] = 0
print(arr_copy)
print(arr)

range of arrays :
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  0  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


#Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

The general format is arr_2d[row][col] or arr_2d[row,col] using the comma notation for clarity.

In [37]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
#Show
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape        #dimension of matrix / array

(3, 3)

In [38]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])


5th element on 2nd dim:  10


In [39]:
arr_2d[1:,1:] 

array([[25, 30],
       [40, 45]])

In [40]:
#Indexing row
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[1][0]

20

In [41]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [42]:

#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [43]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [44]:
#Access 3-D Arrays
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

#Example
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
#Negative Indexing
#Use negative indexing to access an array from the end.

#Example
#Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


Numpy.where():To find the index of value in Numpy Array

numpy.where(condition[, x, y])

In [45]:
import numpy as np
#1-D array
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
print(arr)
 
result = np.where(arr == 15)            # To Get the index of elements with value 15
print('Tuple of arrays returned : ', result)
print("Elements with value 15 exists at following indices", result[0], sep='\n')


[11 12 13 14 15 16 17 15 11 12 14 15 16 17]
Tuple of arrays returned :  (array([ 4,  7, 11], dtype=int64),)
Elements with value 15 exists at following indices
[ 4  7 11]


In [46]:
#index of a value in 2D Numpy array | Matrix
arr = np.array([[11, 12, 13],
                [14, 15, 16],
                [17, 15, 11],
                [12, 14, 15]])
print(arr)


result = np.where(arr == 15)        #  find the indices of element with value 15 in this 2D numpy array 
print('Tuple of arrays returned : ', result)


[[11 12 13]
 [14 15 16]
 [17 15 11]
 [12 14 15]]
Tuple of arrays returned :  (array([1, 2, 3], dtype=int64), array([1, 1, 2], dtype=int64))


In [47]:
# pass multiple conditions to numpy.where().
#For example, get the indices of elements with value less than 16 and greater than 12 i.e.
# Create a numpy array from a list of numbers
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
# Get the index of elements with value less than 16 and greater than 12
result = np.where((arr > 12) & (arr < 16))
print("Elements with value less than 16 and greater than 12 exists at following indices", result, sep='\n')


Elements with value less than 16 and greater than 12 exists at following indices
(array([ 2,  3,  4,  7, 10, 11], dtype=int64),)


numpy.amax():  It is a function to get the maximum value from a Numpy array


In [48]:
import numpy as np
#Find maximum value & its index in a 1D Numpy Array:
#Let’s create a 1D numpy array from a list 
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])

#Get the maximum element from a Numpy array
maxElement = np.amax(arr)
print('Max element from Numpy Array : ', maxElement)
 
#Get the indices of maximum element in numpy array
result = np.where(arr == np.amax(arr))
print('Returned tuple of arrays :', result)
print('List of Indices of maximum element :', result[0])


Max element from Numpy Array :  17
Returned tuple of arrays : (array([ 6, 13], dtype=int64),)
List of Indices of maximum element : [ 6 13]


In [49]:
import numpy
#Find maximum value & its index in a 2D Numpy Array
# Create a 2D Numpy array from list of lists
arr2D = numpy.array([[11, 12, 13],
                     [14, 15, 16],
                     [17, 15, 11],
                     [12, 14, 15]])

#Find max value in complete 2D numpy array
#To find maximum value from complete 2D numpy array we will not pass axis in numpy.amax() i.e.
# Get the maximum value from complete 2D numpy array
maxValue = numpy.amax(arr2D)
print('max value in complete array:', maxValue)

#If we pass axis=0 in numpy.amax() then it returns an array containing max value for each column i.e.
# Get the maximum values of each column i.e. along axis 0
maxInColumns = numpy.amax(arr2D, axis=0)
print('Max value of every column: ', maxInColumns)

#If we pass axis = 1 in numpy.amax() then it returns an array containing max value for each row i.e.
# Get the maximum values of each row i.e. along axis 1
maxInRows = numpy.amax(arr2D, axis=1)
print('Max value of every Row: ', maxInRows)

max value in complete array: 17
Max value of every column:  [17 15 16]
Max value of every Row:  [13 16 17 15]


In [50]:
# numpy.unique():  a function to find the unique elements in a numpy array 


# Find Unique Values from a Numpy Array
# To find the unique values in this array pass the complete array to numpy.unique(). It will return an array of unique values i.e.
# Get unique values in a numpy array
arr = numpy.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)
# Get unique values from a numpy array
uniqueValues = numpy.unique(arr)
print('Unique Values : ',uniqueValues)



#Find Unique Values & their first index position from a Numpy Array
#To get the indices of unique values in numpy array, pass the return_index argument in numpy.unique(), along with array i.e.
arr = numpy.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)
# Get a tuple of unique values & their first index location from a numpy array
uniqueValues, indicesList = numpy.unique(arr, return_index=True)
print('Unique Values : ', uniqueValues)
print('Indices of Unique Values : ', indicesList)

#Get Unique Values & their frequency count from a Numpy Array
#To get the frequency count of unique values in numpy array, pass the return_counts argument in numpy.unique(), along with array i.e.
arr = numpy.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)
# Get a tuple of unique values & their frequency in numpy array
uniqueValues, occurCount = numpy.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)


Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Indices of Unique Values :  [ 0  2  3  4  5  6  7 12]
Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Occurrence Count :  [3 2 2 2 1 1 1 1]


In [51]:
#Find unique values, rows & columns in a 2D numpy array
#We can also pass a 2D numpy array to numpy.unique() to get the unique values i.e.
# Create a 2D numpy array
arr2D = numpy.array([[11, 11, 12,11] ,[ 13, 11, 12,11] , [ 16, 11, 12, 11],  [11, 11, 12, 11]])
print('Original Array :' , arr2D, sep='\n')
# Get unique values from complete 2D array
uniqueValues = numpy.unique(arr2D)
print('Unique Values : ', uniqueValues)


#Get unique Rows :
# Get unique rows from complete 2D numpy array
uniqueRows = numpy.unique(arr2D, axis=0)
print('Unique Rows : ', uniqueRows, sep='\n')


#Get unique Columns :
# Get unique columns from  2D numpy array
uniqueColumns = numpy.unique(arr2D, axis=1)
print('Unique Columns : ', uniqueColumns, sep='\n')


#Get unique Columns & index position :
# Get unique columns  & occurrence count from a 2D numpy array
uniqueColumns, occurCount = numpy.unique(arr2D, axis=1, return_counts=True)
print('Unique Columns : ', uniqueColumns, sep='\n')
print('Unique Columns Occurrence : ', occurCount, sep='\n')


Original Array :
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Values :  [11 12 13 16]
Unique Rows : 
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]
Unique Columns : 
[[11 11 12]
 [11 13 12]
 [11 16 12]
 [11 11 12]]
Unique Columns : 
[[11 11 12]
 [11 13 12]
 [11 16 12]
 [11 11 12]]
Unique Columns Occurrence : 
[2 1 1]


In [54]:
# numpy.amin() :  a function to get the minimum value from a Numpy array 


In [55]:
#Find minimum value & it’s index in a 1D Numpy Array:
#Let’s create a 1D numpy array from a list 
arr = numpy.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
# Get the minimum element from a Numpy array
minElement = numpy.amin(arr)
print('Minimum element from Numpy Array : ', minElement)


Minimum element from Numpy Array :  11


In [56]:
#Find minimum value & it’s index in a 2D Numpy Array
#Let’s create a 2D numpy array .
# Create a 2D Numpy array from list of lists
arr2D = numpy.array([[11, 12, 13],
                     [14, 15, 16],
                     [17, 15, 11],
                     [12, 14, 15]])

arr2D
# Get the minimum value from complete 2D numpy array
minValue = numpy.amin(arr2D)


#Find min values along the axis in 2D numpy array | min in rows or columns:
#If we pass axis=0 in numpy.amin() then it returns an array containing min value for each column i.e.
# Get the minimum values of each column i.e. along axis 0
minInColumns = numpy.amin(arr2D, axis=0)
print('min value of every column: ', minInColumns)

# Get the minimum values of each row i.e. along axis 1
minInRows = numpy.amin(arr2D, axis=1)
print('min value of every Row: ', minInRows)


min value of every column:  [11 12 11]
min value of every Row:  [11 14 11 12]


To get Numpy Array Dimensions using numpy.ndarray.shape & numpy.ndarray.size() 

Get the Dimensions of a Numpy array using ndarray.shape()
#numpy.ndarray.shape

Python’s Numpy module provides a function to get the number of elements in a Numpy array along axis i.e.

#numpy.size(arr, axis=None)

In [57]:
#Get Dimensions of a 2D numpy array using ndarray.shape
#Let’s create a 2D Numpy array i.e.
# Create a 2D Numpy array list of list
arr2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
print('2D Numpy Array')
print(arr2D)

2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]


In [58]:
#Get number of rows in this 2D numpy array i.e.
# get number of rows in 2D numpy array
numOfRows = arr2D.shape[0]
print('Number of Rows : ', numOfRows)


Number of Rows :  3


In [59]:
# get number of columns in 2D numpy array
numOfColumns = arr2D.shape[1]
print('Number of Columns : ', numOfColumns)
# get total number of elements in this 2D numpy array,
print('Total Number of elements in 2D Numpy array : ', arr2D.shape[0] * arr2D.shape[1])

Number of Columns :  4
Total Number of elements in 2D Numpy array :  12


In [60]:
#Get Dimensions of a 1D numpy array using ndarray.shape
#Let’s create a 1D Numpy array i.e.
# Create a Numpy array from list of numbers
arr = np.array([4, 5, 6, 7, 8, 9, 10, 11])

#Get number of elements of this 1D numpy array i.e.
print('Shape of 1D numpy array : ', arr.shape)
print('length of 1D numpy array : ', arr.shape[0])


Shape of 1D numpy array :  (8,)
length of 1D numpy array :  8


Get the Dimensions of a Numpy array using numpy.shape()

Python’s Numpy module provides a function to get the number of elements in a Numpy array along axis i.e.

#numpy.size(arr, axis=None)

Args: It accepts the numpy array and also the axis along which it needs to count the elements.If axis is not passed then returns the total number of arguments.

Returns: The number of elements along the passed axis.


In [61]:
#Get Dimensions of a 2D numpy array using numpy.size()
#Let’s create a 2D Numpy array i.e.
# Create a 2D Numpy array list of list
arr2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
print('2D Numpy Array')
print(arr2D)

2D Numpy Array
[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]


In [62]:
#Get number of rows and columns of this 2D numpy array:
# get number of rows in 2D numpy array
numOfRows = np.size(arr2D, 0)


# get number of columns in 2D numpy array
numOfColumns = np.size(arr2D, 1)
print('Number of Rows : ', numOfRows)
print('Number of Columns : ', numOfColumns)


#Get total number of elements in this 2D numpy array:
print('Total Number of elements in 2D Numpy array : ', np.size(arr2D))


Number of Rows :  3
Number of Columns :  4
Total Number of elements in 2D Numpy array :  12


In [63]:
#Get Dimensions of a 3D numpy array using numpy.size()
# Create a 3D Numpy array list of list of list
arr3D = np.array([ [[11, 12, 13, 11], [21, 22, 23, 24], [31, 32, 33, 34]],
                 [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]] ])
print(arr3D)

#get number of elements per axis in 3D numpy array i.e.
print('Axis 0 size : ', np.size(arr3D, 0))
print('Axis 1 size : ', np.size(arr3D, 1))
print('Axis 2 size : ', np.size(arr3D, 2))


[[[11 12 13 11]
  [21 22 23 24]
  [31 32 33 34]]

 [[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]]
Axis 0 size :  2
Axis 1 size :  3
Axis 2 size :  4


#Selecting elements from Numpy Array

Select element or sub array by index from numpy array

Select rows / columns by index from a 2D numpy array


In [64]:
# http://playground.tensorflow.org/#activation=tanh&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.03&regularizationRate=0&noise=0&networkShape=4,2&seed=0.52744&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false

In [65]:
# Select an element or sub array by index from a Numpy Array
# Let’s create a Numpy Array using numpy.arange()
import numpy as np
npArray = np.arange(1, 20, 2)
print(npArray)

# To select an element from Numpy Array , we can use [] operator i.e.
# ndarray[index]

# Select an element at index 2 (Index starts from 0)
elem = npArray[2]
print('Element at 2nd index  : ' , elem)

#Select elements from beginning to index 3
subArray = npArray[:4]

#Select elements from 2nd index to end
subArray = npArray[2 : ]
print('element from 2nd index to end :' , subArray)
print(subArray)
#We can also select a sub array from Numpy Array using [] operator i.e.
# ndArray[first:last]

# Select elements from index 1 to 6
subArray = npArray[1:7]
print('elements from index 1 to 6: ' , subArray)

[ 1  3  5  7  9 11 13 15 17 19]
Element at 2nd index  :  5
element from 2nd index to end : [ 5  7  9 11 13 15 17 19]
[ 5  7  9 11 13 15 17 19]
elements from index 1 to 6:  [ 3  5  7  9 11 13]


In [66]:
# Select rows / columns by index from a 2D Numpy Array 

In [67]:
#create a 2d Numpy Array by passing a list of lists to numpy.array()
# Create a 2D Numpy adArray with 3 rows & 3 columns | Matrix
nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(nArr2D)
# to Select a single element from 2D Numpy Array by index
# ndArray[row_index][column_index]

# Select element at row index 1 & column index 2
num = nArr2D[1][2]
print('element at row index 1 & column index 2 is : ' , num)
# OR cooma separated 
num = nArr2D[1, 2]
print('element at row index 1 & column index 2 is : ', num)


[[21 22 23]
 [11 22 33]
 [43 77 89]]
element at row index 1 & column index 2 is :  33
element at row index 1 & column index 2 is :  33


In [68]:
#Select Rows by Index from a 2D Numpy Array
#We can call [] operator to select a single or multiple row. To select a single row use,
# ndArray[row_index]

#To select multiple rows use,
# ndArray[start_index: end_index ,  :]

nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(nArr2D)

# Select a Row at index 1
row = nArr2D[1]
print('Contents of Row at Index 1 : ' , row)

# Select multiple rows from index 1 to 2
rows = nArr2D[1:3, :]
print('Rows from Index 1 to 2 :' , rows)

[[21 22 23]
 [11 22 33]
 [43 77 89]]
Contents of Row at Index 1 :  [11 22 33]
Rows from Index 1 to 2 : [[11 22 33]
 [43 77 89]]


In [69]:
Select Columns by Index from a 2D Numpy Array
To select a single column use,
#ndArray[ : , column_index]


To select multiple columns use,
#ndArray[ : , start_index: end_index]

SyntaxError: invalid syntax (<ipython-input-69-7f233bcb0cba>, line 1)

In [70]:
nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(nArr2D)

# Select a column at index 1
column = nArr2D[:, 1]
print('Contents of Column at Index 1 : ', column)

# Select multiple columns from index 1 to 2
columns = nArr2D[: , 1:3]
print('Column from Index 1 to 2 :')
print(columns)

# Select multiple columns from index 1 to last index
columns = nArr2D[:, 1:]
print(columns)

[[21 22 23]
 [11 22 33]
 [43 77 89]]
Contents of Column at Index 1 :  [22 22 77]
Column from Index 1 to 2 :
[[22 23]
 [22 33]
 [77 89]]
[[22 23]
 [22 33]
 [77 89]]


In [71]:
Select a Sub Matrix or 2d Numpy Array from another 2D Numpy Array
To select sub 2d Numpy Array we can pass the row & column index range in [] operator i.e.
ndArray[start_row_index : end_row_index , start_column_index : end_column_index]

It will return a sub 2D Numpy Array for given row and column range.


SyntaxError: invalid syntax (<ipython-input-71-7c5b2cc7ff6f>, line 1)

In [72]:
nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print('numpy array :' , nArr2D)

# Select a sub 2D array from row indices 1 to 2 & column indices 1 to 2
sub2DArr = nArr2D[1:3, 1:3]
print('Sub 2d Array :')
print(sub2DArr)


# Select row at index 1 from 2D array
row = nArr2D[1]
print(row)

# Change all the elements in selected sub array to 100
row[:] = 100
print(row)

numpy array : [[21 22 23]
 [11 22 33]
 [43 77 89]]
Sub 2d Array :
[[22 33]
 [77 89]]
[11 22 33]
[100 100 100]


In [74]:
#ndarray.copy() : to the copy instead of view in sub array use copy() function.

In [75]:
nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(nArr2D)

# Select a copy of row at index 1 from 2D array
row = nArr2D[2].copy()
print(row)

[[21 22 23]
 [11 22 33]
 [43 77 89]]
[43 77 89]


In [77]:
# command : np.delete(): Remove items/rows/columns from Numpy Array
# a method to delete elements from a numpy array based on index position 
'''numpy.delete(arr, obj, axis=None)
Arguments:

arr : Numpy array from which elements needs to be deleted.
obj : Index position or list of index positions of items to be deleted from numpy array arr.
axis : Axis along which we want to delete.
If 1 then delete columns.
If 0 then delete rows.
If None then flatten the array and then apply delete on it.'''

'numpy.delete(arr, obj, axis=None)\nArguments:\n\narr : Numpy array from which elements needs to be deleted.\nobj : Index position or list of index positions of items to be deleted from numpy array arr.\naxis : Axis along which we want to delete.\nIf 1 then delete columns.\nIf 0 then delete rows.\nIf None then flatten the array and then apply delete on it.'

In [78]:
# Create a Numpy array from list of numbers
arr = np.array([4,5,6,7,8,9,10,11])
print(arr)
#delete an element at index position 2 in the above created numpy array,

# Delete element at index position 2
arr = np.delete(arr, 2)
print('Modified Numpy Array by deleting element at index position 2')
print(arr)

#Delete element at index positions 1,2 and 3
arr = np.delete(arr, [1,2,3])         # To delete multiple element 
print('Modified Numpy Array by deleting element at index position 1, 2 &amp; 3')
print(arr)

[ 4  5  6  7  8  9 10 11]
Modified Numpy Array by deleting element at index position 2
[ 4  5  7  8  9 10 11]
Modified Numpy Array by deleting element at index position 1, 2 &amp; 3
[ 4  9 10 11]


In [79]:
numpy.ndarray.sort() : 
numpy.sort()
Another one is a global function in numpy module i.e.
numpy.sort(array, axis=-1, kind='quicksort', order=None)

It accepts a numpy array as an argument and returns a sorted copy of Numpy array.
Important Arguments in both the above functions are,

axis: Axis along which it needs to sort. Default value is -1 i.e. the last axis
kind: Type of sorting algorithm to be used. Values can be ‘mergesort’, ‘heapsort’, ‘stable’ and ‘quicksort’
order: Udes in Structured Numpy array. Can be a single column name or list of column names along which sorting needs to be done.

SyntaxError: invalid syntax (<ipython-input-79-898a244a6838>, line 1)

In [80]:
# Create a Numpy array from list of numbers
arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])

# Sort the numpy array inplace
arr.sort()
print('Sorted Array : ', arr)

Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]


In [81]:
# to sort a numpy array in descending order we need to sort it and then use [::-1] to reverse the sorted array.
arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
print(arr)
# Get a sorted copy of numpy array (Descending Order)
arr = np.sort(arr)[::-1]
print('Sorted Array in Descending Order: ', arr)


[ 6  1  4  2 18  9  3  4  2  8 11]
Sorted Array in Descending Order:  [18 11  9  8  6  4  4  3  2  2  1]


In [82]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',